sudo: required
services:
  - docker

before_install:
  - docker build -t allanweber/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run allanweber/react-test npm test -- --coverage

after_success:
  - docker build -t allanweber/multi-client ./client
  - docker build -t allanweber/multi-nginx ./nginx
  - docker build -t allanweber/multi-server ./server
  - docker build -t allanweber/multi-worker ./worker
  # Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push allanweber/multi-client
  - docker push allanweber/multi-nginx
  - docker push allanweber/multi-server
  - docker push allanweber/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-sa-east-1-030789392814"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
